"""empty message

Revision ID: 49ba906d2609
Revises: ceff7c9a7622
Create Date: 2024-02-23 12:34:45.121941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ba906d2609'
down_revision = 'ceff7c9a7622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_table', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=3000),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.NUMERIC(precision=13),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_table', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.NUMERIC(precision=13),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
