"""empty message

Revision ID: ceff7c9a7622
Revises: dd9d4182d223
Create Date: 2024-02-19 15:57:13.474165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceff7c9a7622'
down_revision = 'dd9d4182d223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_table', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=3000),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.NUMERIC(precision=13),
               type_=sa.String(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_table', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=13),
               type_=sa.NUMERIC(precision=13),
               existing_nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
