"""empty message

Revision ID: dd9d4182d223
Revises: 
Create Date: 2024-02-17 11:11:21.658519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9d4182d223'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_table',
    sa.Column('codes', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('codes'),
    sa.UniqueConstraint('codes')
    )
    op.create_table('text_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('delete_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_table')
    op.drop_table('code_table')
    # ### end Alembic commands ###
